"""Convert HaWoR world-space output to an OpenArm bimanual pose NPZ."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from openarm_retarget.hawor_adapter import convert_hawor_world_to_bimanual_pose
from openarm_retarget.io import save_npz


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert HaWoR world_space_res.pth into bimanual hand pose."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("external_repos/HaWoR/example/video_0/world_space_res.pth"),
        help="HaWoR world_space_res.pth generated by demo.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "outputs/external_trials/hawor_world/video_0_hawor_world_hand_pose.npz"
        ),
        help="Output bimanual hand-pose NPZ.",
    )
    parser.add_argument(
        "--hawor-root",
        type=Path,
        default=Path("external_repos/HaWoR"),
        help="HaWoR checkout used for MANO decoding.",
    )
    parser.add_argument("--fps", type=float, default=30.0)
    parser.add_argument(
        "--workspace-scale",
        type=float,
        default=0.5,
        help="Meters mapped to one normalized human-coordinate unit.",
    )
    parser.add_argument(
        "--no-mano",
        action="store_true",
        help="Use wrist-based fingertip proxies instead of MANO joints.",
    )
    parser.add_argument(
        "--cuda-mano",
        action="store_true",
        help="Decode MANO joints on CUDA inside the HaWoR container.",
    )
    parser.add_argument(
        "--no-normalize",
        action="store_true",
        help="Write HaWoR metric/world coordinates directly.",
    )
    parser.add_argument(
        "--no-world-axis",
        action="store_true",
        help="Skip HaWoR demo's world-visualization axis transform.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    pose = convert_hawor_world_to_bimanual_pose(
        args.input,
        fps=args.fps,
        hawor_root=args.hawor_root,
        use_mano=not args.no_mano,
        use_cuda=args.cuda_mano,
        apply_world_axis=not args.no_world_axis,
        normalize=not args.no_normalize,
        workspace_scale=args.workspace_scale,
    )
    save_npz(
        args.output,
        pose,
        stage="hawor_world_bimanual_hand_pose",
        metadata={
            "source": str(args.input),
            "hawor_root": str(args.hawor_root),
            "fps": args.fps,
            "workspace_scale": args.workspace_scale,
            "mano": not args.no_mano,
            "normalized": not args.no_normalize,
        },
    )
    summary = {
        "output": str(args.output),
        "frames": int(len(pose["timestamps"])),
        "left_valid_ratio": float(np.mean(pose["left_valid"])),
        "right_valid_ratio": float(np.mean(pose["right_valid"])),
        "left_wrist_first": pose["left_wrist"][0].tolist(),
        "right_wrist_first": pose["right_wrist"][0].tolist(),
    }
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
